# Generated by Django 5.2.9 on 2025-12-23 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('subtitle', models.TextField(verbose_name='Bajada/Subtítulo')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL Imagen')),
                ('content', models.JSONField(default=list, verbose_name='Contenido')),
                ('paragraphs_count', models.IntegerField(default=0, verbose_name='Nº Párrafos')),
                ('publication_date', models.CharField(max_length=100, verbose_name='Fecha Publicación')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('category', models.CharField(max_length=200, verbose_name='Categoría')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Extracción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['url'], name='news_articl_url_957495_idx'), models.Index(fields=['scraped_at'], name='news_articl_scraped_e0f02b_idx'), models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'), models.Index(fields=['author'], name='news_articl_author_107790_idx')],
            },
        ),
    ]
