# Generated by Django 5.2.9 on 2026-01-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-scraped_at'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
