# Generated by Django 5.2.9 on 2026-01-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Publicación'),
        ),
    ]
