# Generated by Django 5.2.9 on 2026-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on_instagram',
            field=models.BooleanField(default=False, verbose_name='Publicado en Instagram'),
        ),
    ]
