# Generated by Django 5.2.9 on 2026-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Mínimo 5, Máximo 1000 caracteres', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Máximo 100 caracteres', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='Mínimo 2 caracteres, máximo 100 caracteres', max_length=100, verbose_name='Nombre'),
        ),
    ]
