# Generated by Django 5.2.9 on 2026-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_comment_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Visitas totales')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Contador de visitas',
                'verbose_name_plural': 'Contadores de visitas',
                'ordering': ['-date'],
            },
        ),
    ]
